### ISSUE TITLE
Create community website MVP

### ISSUE THREAD

**Issue by aschrijver** [humanetech-community/community-hub#12]
This is a top-level issue to track development of the Minimum Viable Product of the Community Website. It should be finished by 23th of April.

## Tasks

- [x] MVP Quick fixes to remove e.g. broken links and show some content in empty pages
  - [x] Remove the tags + categories in current blog posts (non-MVP) (#48)
  - [x] Add contents to the "Docs" toplevel page to introduce focus area's (#49)
  - [x] Add contents to the "Activities" toplevel page to introduce our projects (#50)
  - [ ] ~~Temporarily disable the Previous / Next nagivation (non-MVP)~~ (#51)
- [x] Adapt existing draft website to the new Mission and Vision (#13)
- [x] Create blog entries with important Community Team announcements
  - [x] Create a blog entry for the important CHT Livestream announcement (#43)
  - [x] Create a blog entry calling for members to join and 'Be a Builder' (#45)
  - [x] Create 'Position statement' blog entry with HTC Open Canvas (#54)
- [x] Create short summary text intros for each pyramids on index.html (#15)
  - [x] Update landing page short pyramid description texts (#21)
- [x] Create an area on the landing page for active content (#8)
- [ ] Create text descriptions for each pyramid category on their specific pages (#20)
- [x] Move to use 'Authors' only for attributed (Blog) pages, and have a generic site author (#18)
- [x] Write an introduction in Markdown that gives an overview of HTC (#17)
  - [x] Add the Markdown as a blog document to the website
- [ ]  Write a short About document in Markdown that gives history + context to the HTC
  - [x] Add left-hand navigation for the About section sub-pages (#22)
  - [ ] ~~Add a Teams section where existing forum groups are introduced~~ (non-MVP)
  - [x] Add a FAQ as a sub-page of About page (take forum FAQ as input) 
  - [x] Add a Privacy Policy as a sub-page of About page (and a link on landing page) (#31)
  - [x] Add Code of Conduct latest version as a sub-page of About page
  - [x] Add a reference to Code of Conduct to forum menu (Admin task)
- [ ] Compile a shortlist of references + description in the Resources page
  - [ ] Add references to important / most relevant external organizations
  - [x] Add a list of most relevant articles, research papers, etc.
  - [x] Add a list of most relevant books (#27)
  - [ ] Add a list of 'Our Stories' with links to some representative forum member bio introductions (#25)
- [x] Write the text for the [Join Our Community](https://humanetech.community/join/) page (#19)
- [ ] Cooperate with CHT to streamline onboarding of new members
  - [x] Ask CHT, David Jay for details on the April 23rd event, so we can tailor the message
  - [ ] Discuss ways of leading members to the Community Hub
  - [ ] Adapt humanetech.com website so there is clearer reference to HTC
- [x] Enable full-text search using default Lunr search functionality (#32)
- [x] Adapt the links sharing feature with proper social media channels (#36)
- [x] Add the ability to show Discourse comments threads (#44)

**Comment by aschrijver** [comment]
# Requirements for the landing page

- Conveys the message that is in [**Be a Builder :heart: Help Improve Wellbeing, Freedom and Society**](https://community.humanetech.com/t/be-a-builder-help-improve-wellbeing-freedom-and-society/3322)

- Mentions and explains the Vision of _"Ubiquitous Humane Technology that Stimulates Humans to Flourish and Humanity to Thrive."_

- Mentions and explains the Mission of _"We Promote Solutions that Improve Wellbeing, Freedom and Society."_

- Introduces the concepts of The Pyramids of Humane Technology
  - Highlights the solution focus i.e. _"awareness of solutions"_
  - Highlights the four focus areas i.e. 4 pyramids
  - Highlights the relation _Humane Technnology --> Human Flourishing_ i.e. the 5th compound Pyramid of Human Flourishing

- We can use the simple colors of current pyramid images as part of the base palette and derive tints and shades from them

**Comment by aschrijver** [comment]
When taking up any of the issues from the top-level list, then do the following:

- Create a new Github issue, and use the same title as in the list above.
- Add a link to this issue in the issue you are creating (creates cross-reference)
- Create a short task description of what you are about to do, so others are in the loop when reading
- Assign the issue to yourself, and drag the issue in the To-Do column of the [project board](https://github.com/humanetech-community/community-hub/projects/1)
- When starting to work on it, place it (by dragging) in the 'In progress' column.

**Comment by aschrijver** [comment]
@micheleminno you removed content from the summary.. like adding search. Was this by accident? I want to rollback the content by 2 revisions.

**Comment by micheleminno** [comment]
I only edited a subitem.. yes rollback.

**Comment by aschrijver** [comment]
Hmm, Can't seem to be able to rollback. I'll edit a new revision.

**Edit**: Done. Had to edit by hand. Weird that Github does not provide a rollback. Or maybe the UI is confusing, so Deleting Rollback means delete all revisions that come after the current one.

**Comment by aschrijver** [comment]
PS. The issue probably caused because you need to refresh the page before clicking Edit (usually GH gives a warning when trying to Save however).

**Comment by micheleminno** [comment]
Ok I will do it (I didn’t notice any warning though..).

**Comment by aschrijver** [comment]
The [MVP Community Hub](https://github.com/humanetech-community/community-hub/projects/1) project is now closed.
