### ISSUE TITLE
Finish Activities section according to new community organization

### ISSUE THREAD

**Issue by aschrijver** [humanetech-community/community-hub#67]
This is a top-level issue and consists of the following tasks:

- [x] Create sidebar navigation for Activities page (#65)
- [x] Move documentation from Awareness Program repo to Community Hub (#66)
  - [x] Create campaign themes pages and update 'Campaign themes' page
  - [x] Create campaigns pages and update 'Campaigns' page
  - [x] Create campaigns deliverables pages and update 'Campaign deliverables' page
- [x] Create Meetups overview (transfer from forum)
  - [x] Create Events page and add tables for upcoming / past events
  - [x] Create Meetup Chapters page an add table with existing chapters (#75)
- [ ] Collect Ideas from the forum and create Ideas section
  - [ ] Add the [Humane Tech Certification](https://community.humanetech.com/t/778) project to Ideas section
